version: '3.0'

services:
   wordpress:
     image: wordpress
     ports:
       - "80:80"
     environment:
       WORDPRESS_DB_HOST: wordpress:8033
       WORDPRESS_DB_HOST: 172.23.0.2:3306
       WORDPRESS_DB_NAME: marcusmm
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: somewordpress
     
      